### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by intendo** [nhuyvan1106/facebook-flights#1]
When I try to run it with the newest updates on commit, https://github.com/nhuyvan1106/facebook-flights/commit/fc299b0ea872ac2d5f0c657876e98e7be621d155, I get the following errors:

08:51 ng serve
Your global Angular CLI version (1.7.2) is greater than your local
version (1.7.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-07T16:51:39.062Z
Hash: 8c216215b35014ef5eb0
Time: 2630ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 49.8 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in node_modules/@ngrx/store/src/ng2.d.ts(1,10): error TS2305: Module '"/Users/d3c572/git/facebook-flights/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
src/app/app.module.ts(40,17): error TS2339: Property 'forRoot' does not exist on type 'typeof StoreModule'.
src/app/flight-details/flights/flight-details-selectors.ts(1,10): error TS2305: Module '"/Users/d3c572/git/facebook-flights/node_modules/@ngrx/store/index"' has no exported member 'createSelector'.
src/app/root-reducers.ts(1,10): error TS2305: Module '"/Users/d3c572/git/facebook-flights/node_modules/@ngrx/store/index"' has no exported member 'ActionReducerMap'.

webpack: Failed to compile.

**Comment by nhuyvan1106** [comment]
You should try
npm install, then
npm start

**Comment by intendo** [comment]
That worked, thanks!
